import { TerrainTile } from "../models/sprite-tile.model";

export const RockWall: TerrainTile[] = [
    {
      id: 'FrontCenter',
      topWith: {x: 1, y: 3},
      expandWith: {x: 1, y: 4},
      baseWith: {x: 1, y: 5},
      drawWhen: {
        topNeighbor: true,
        topRightNeighbor: null,
        rightNeighbor: true,
        bottomRightNeighbor: false,
        bottomNeighbor: false,
        bottomLeftNeighbor: false,
        leftNeighbor: true,
        topLeftNeighbor: null,
      },
    },
    {
      id: 'FrontLeft',
      topWith: {x: 0, y: 3},
      expandWith: {x: 0, y: 4},
      baseWith: {x: 0, y: 5},
      drawWhen: {
        topNeighbor: true,
        topRightNeighbor: null,
        rightNeighbor: true,
        bottomRightNeighbor: null,
        bottomNeighbor: false,
        bottomLeftNeighbor: false,
        leftNeighbor: false,
        topLeftNeighbor: null,
      },
    },
    {
      id: 'FrontRight',
      topWith: {x: 2, y: 3},
      expandWith: {x: 2, y: 4},
      baseWith: {x: 2, y: 5},
      drawWhen: {
        topNeighbor: true,
        topRightNeighbor: false,
        rightNeighbor: false,
        bottomRightNeighbor: false,
        bottomNeighbor: false,
        bottomLeftNeighbor: null,
        leftNeighbor: true,
        topLeftNeighbor: null,
      },
    },
    {
      id: 'MidLeft',
      topWith: {x: 0, y: 2},
      drawWhen: {
        topNeighbor: true,
        topRightNeighbor: null,
        rightNeighbor: true,
        bottomRightNeighbor: null,
        bottomNeighbor: true,
        bottomLeftNeighbor: null,
        leftNeighbor: false,
        topLeftNeighbor: null,
      },
    },
      {
        id: 'MidCenter',
        default: true,
        hasTerrainOnTop: true,
        topWith: {x: 3, y: 12 },
        drawWhen: {
          topNeighbor: true,
          topRightNeighbor: true,
          rightNeighbor: true,
          bottomRightNeighbor: true,
          bottomNeighbor: true,
          bottomLeftNeighbor: true,
          leftNeighbor: true,
          topLeftNeighbor: true,
        },
      },
      {
        id: 'MidRight',
        topWith: {x: 0, y: 1 },
        drawWhen: {
          topNeighbor: true,
          topRightNeighbor: null,
          rightNeighbor: false,
          bottomRightNeighbor: null,
          bottomNeighbor: true,
          bottomLeftNeighbor: null,
          leftNeighbor: true,
          topLeftNeighbor: null,
        },
      },
      {
        id: 'TopLeft',
        topWith: {x: 0, y: 0},
        drawWhen: {
          topNeighbor: false,
          topRightNeighbor: null,
          rightNeighbor: true,
          bottomRightNeighbor: true,
          bottomNeighbor: true,
          bottomLeftNeighbor: null,
          leftNeighbor: false,
          topLeftNeighbor: false,
        },
      },
      {
        id: 'TopCenter',
        topWith: {x: 1, y: 0 },
        drawWhen: {
          topNeighbor: false,
          topRightNeighbor: null,
          rightNeighbor: true,
          bottomRightNeighbor: null,
          bottomNeighbor: true,
          bottomLeftNeighbor: null,
          leftNeighbor: true,
          topLeftNeighbor: null,
        },
      },
      {
        id: 'TopRight',
        topWith: {x: 2, y: 0 },
        drawWhen: {
          topNeighbor: false,
          topRightNeighbor: null,
          rightNeighbor: false,
          bottomRightNeighbor: null,
          bottomNeighbor: true,
          bottomLeftNeighbor: null,
          leftNeighbor: true,
          topLeftNeighbor: null,
        },
      },
      {
        id: 'FontLeftAttach',
        topWith: {x: 3, y: 0},
        expandWith: {x: 3, y: 1},
        baseWith: {x: 3, y: 2 },
        drawWhen: {
          topNeighbor: true,
          topRightNeighbor: null,
          rightNeighbor: true,
          bottomRightNeighbor: null,
          bottomNeighbor: false,
          bottomLeftNeighbor: true,
          leftNeighbor: true,
          topLeftNeighbor: null,
        },
      },
      {
        id: 'FontRightAttach',
        topWith: {x: 4, y: 0},
        expandWith: {x: 4, y: 1},
        baseWith: {x: 4, y: 2 },
        drawWhen: {
          topNeighbor: true,
          topRightNeighbor: null,
          rightNeighbor: true,
          bottomRightNeighbor: true,
          bottomNeighbor: false,
          bottomLeftNeighbor: null,
          leftNeighbor: true,
          topLeftNeighbor: null,
        },
      },
      {
        id: 'FontRightAdjacentAttach',
        topWith: {x: 4, y: 3},
        expandWith: {x: 4, y: 4},
        baseWith: {x: 4, y: 5 },
        drawWhen: {
          topNeighbor: true,
          topRightNeighbor: true,
          rightNeighbor: false,
          bottomRightNeighbor: null,
          bottomNeighbor: false,
          bottomLeftNeighbor: null,
          leftNeighbor: true,
          topLeftNeighbor: null,
        },
      },
      {
        id: 'bottomLeftFillerSquare',
        topWith: {x: 1, y: 2 },
        drawWhen: {
          topNeighbor: true,
          topRightNeighbor: true,
          rightNeighbor: true,
          bottomRightNeighbor: true,
          bottomNeighbor: true,
          bottomLeftNeighbor: false,
          leftNeighbor: true,
          topLeftNeighbor: true,
        },
      },
      {
        id: 'bottomRightFillerSquare',
        topWith: {x: 2, y: 2 },
        drawWhen: {
          topNeighbor: true,
          topRightNeighbor: true,
          rightNeighbor: true,
          bottomRightNeighbor: false,
          bottomNeighbor: true,
          bottomLeftNeighbor: true,
          leftNeighbor: true,
          topLeftNeighbor: true,
        },
      },
      {
        id: 'TopLeftFillerSquare',
        topWith: {x: 1, y: 1},
        drawWhen: {
          topNeighbor: true,
          topRightNeighbor: true,
          rightNeighbor: true,
          bottomRightNeighbor: true,
          bottomNeighbor: true,
          bottomLeftNeighbor: true,
          leftNeighbor: true,
          topLeftNeighbor: false,
        },
      },
      {
        id: 'TopRightFillerSquare',
        topWith: {x: 2, y: 1 },
        drawWhen: {
          topNeighbor: true,
          topRightNeighbor: false,
          rightNeighbor: true,
          bottomRightNeighbor: true,
          bottomNeighbor: true,
          bottomLeftNeighbor: true,
          leftNeighbor: true,
          topLeftNeighbor: true,
        },
      },
    ];