import { TerrainTile } from "../models/sprite-tile.model";

export const RockWall: TerrainTile[] = [
    {
      id: 'FrontCenter',
      spritePosX: 1,
      spritePosY: 3,
      spriteSize: {x: 16, y: 48},
      offsetX: 0,
      offsetY: -32,
      drawWhen: {
        topNeighbor: true,
        topRightNeighbor: null,
        rightNeighbor: true,
        bottomRightNeighbor: false,
        bottomNeighbor: false,
        bottomLeftNeighbor: false,
        leftNeighbor: true,
        topLeftNeighbor: null,
      },
    },
    {
      id: 'FrontLeft',
      spritePosX: 0,
      spritePosY: 3,
      spriteSize: {x: 16, y: 48},
      offsetX: 0,
      offsetY: -32,
      drawWhen: {
        topNeighbor: true,
        topRightNeighbor: null,
        rightNeighbor: true,
        bottomRightNeighbor: null,
        bottomNeighbor: false,
        bottomLeftNeighbor: false,
        leftNeighbor: false,
        topLeftNeighbor: null,
      },
    },
    {
      id: 'FrontRight',
      spritePosX: 2,
      spritePosY: 3,
      spriteSize: {x: 16, y: 48},
      offsetX: 0,
      offsetY: -32,
      drawWhen: {
        topNeighbor: true,
        topRightNeighbor: false,
        rightNeighbor: false,
        bottomRightNeighbor: false,
        bottomNeighbor: false,
        bottomLeftNeighbor: null,
        leftNeighbor: true,
        topLeftNeighbor: null,
      },
    },
    {
      id: 'MidLeft',
      spritePosX: 0,
      spritePosY: 2,
      spriteSize: {x: 16, y: 16},
      offsetX: 0,
      offsetY: -32,
      drawWhen: {
        topNeighbor: true,
        topRightNeighbor: null,
        rightNeighbor: true,
        bottomRightNeighbor: null,
        bottomNeighbor: true,
        bottomLeftNeighbor: null,
        leftNeighbor: false,
        topLeftNeighbor: null,
      },
    },
      {
        id: 'MidCenter',
        spritePosX: 3,
        spritePosY: 12,
        spriteSize: {x: 16, y: 16},
        offsetX: 0,
        offsetY: -32,
        default: true,
        drawWhen: {
          topNeighbor: true,
          topRightNeighbor: true,
          rightNeighbor: true,
          bottomRightNeighbor: true,
          bottomNeighbor: true,
          bottomLeftNeighbor: true,
          leftNeighbor: true,
          topLeftNeighbor: true,
        },
      },
      {
        id: 'MidRight',
        spritePosX: 0,
        spritePosY: 1,
        spriteSize: {x: 16, y: 16},
        offsetX: 0,
        offsetY: -32,
        drawWhen: {
          topNeighbor: true,
          topRightNeighbor: null,
          rightNeighbor: false,
          bottomRightNeighbor: null,
          bottomNeighbor: true,
          bottomLeftNeighbor: null,
          leftNeighbor: true,
          topLeftNeighbor: null,
        },
      },
      {
        id: 'TopLeft',
        spritePosX: 0,
        spritePosY: 0,
        spriteSize: {x: 16, y: 16},
        offsetX: 0,
        offsetY: -32,
        drawWhen: {
          topNeighbor: false,
          topRightNeighbor: null,
          rightNeighbor: true,
          bottomRightNeighbor: true,
          bottomNeighbor: true,
          bottomLeftNeighbor: null,
          leftNeighbor: false,
          topLeftNeighbor: false,
        },
      },
      {
        id: 'TopCenter',
        spritePosX: 1,
        spritePosY: 0,
        spriteSize: {x: 16, y: 16},
        offsetX: 0,
        offsetY: -32,
        drawWhen: {
          topNeighbor: false,
          topRightNeighbor: null,
          rightNeighbor: true,
          bottomRightNeighbor: null,
          bottomNeighbor: true,
          bottomLeftNeighbor: null,
          leftNeighbor: true,
          topLeftNeighbor: null,
        },
      },
      {
        id: 'TopRight',
        spritePosX: 2,
        spritePosY: 0,
        spriteSize: {x: 16, y: 16},
        offsetX: 0,
        offsetY: -32,
        drawWhen: {
          topNeighbor: false,
          topRightNeighbor: null,
          rightNeighbor: false,
          bottomRightNeighbor: null,
          bottomNeighbor: true,
          bottomLeftNeighbor: null,
          leftNeighbor: true,
          topLeftNeighbor: null,
        },
      },
      {
        id: 'FontLeftAttach',
        spritePosX: 3,
        spritePosY: 0,
        spriteSize: {x: 16, y: 48},
        offsetX: 0,
        offsetY: -32,
        drawWhen: {
          topNeighbor: true,
          topRightNeighbor: null,
          rightNeighbor: true,
          bottomRightNeighbor: null,
          bottomNeighbor: false,
          bottomLeftNeighbor: true,
          leftNeighbor: true,
          topLeftNeighbor: null,
        },
      },
      {
        id: 'FontRightAttach',
        spritePosX: 4,
        spritePosY: 0,
        spriteSize: {x: 16, y: 48},
        offsetX: 0,
        offsetY: -32,
        drawWhen: {
          topNeighbor: true,
          topRightNeighbor: null,
          rightNeighbor: true,
          bottomRightNeighbor: true,
          bottomNeighbor: false,
          bottomLeftNeighbor: null,
          leftNeighbor: true,
          topLeftNeighbor: null,
        },
      },
      {
        id: 'FontRightAdjacentAttach',
        spritePosX: 4,
        spritePosY: 3,
        spriteSize: {x: 16, y: 48},
        offsetX: 0,
        offsetY: -32,
        drawWhen: {
          topNeighbor: true,
          topRightNeighbor: true,
          rightNeighbor: false,
          bottomRightNeighbor: null,
          bottomNeighbor: false,
          bottomLeftNeighbor: null,
          leftNeighbor: true,
          topLeftNeighbor: null,
        },
      },
      {
        id: 'bottomLeftFillerSquare',
        spritePosX: 1,
        spritePosY: 2,
        spriteSize: {x: 16, y: 16},
        offsetX: 0,
        offsetY: -32,
        drawWhen: {
          topNeighbor: true,
          topRightNeighbor: true,
          rightNeighbor: true,
          bottomRightNeighbor: true,
          bottomNeighbor: true,
          bottomLeftNeighbor: false,
          leftNeighbor: true,
          topLeftNeighbor: true,
        },
      },
      {
        id: 'bottomRightFillerSquare',
        spritePosX: 2,
        spritePosY: 2,
        spriteSize: {x: 16, y: 16},
        offsetX: 0,
        offsetY: -32,
        drawWhen: {
          topNeighbor: true,
          topRightNeighbor: true,
          rightNeighbor: true,
          bottomRightNeighbor: false,
          bottomNeighbor: true,
          bottomLeftNeighbor: true,
          leftNeighbor: true,
          topLeftNeighbor: true,
        },
      },
      {
        id: 'TopLeftFillerSquare',
        spritePosX: 1,
        spritePosY: 1,
        spriteSize: {x: 16, y: 16},
        offsetX: 0,
        offsetY: -32,
        drawWhen: {
          topNeighbor: true,
          topRightNeighbor: true,
          rightNeighbor: true,
          bottomRightNeighbor: true,
          bottomNeighbor: true,
          bottomLeftNeighbor: true,
          leftNeighbor: true,
          topLeftNeighbor: false,
        },
      },
      {
        id: 'TopRightFillerSquare',
        spritePosX: 2,
        spritePosY: 1,
        spriteSize: {x: 16, y: 16},
        offsetX: 0,
        offsetY: -32,
        drawWhen: {
          topNeighbor: true,
          topRightNeighbor: false,
          rightNeighbor: true,
          bottomRightNeighbor: true,
          bottomNeighbor: true,
          bottomLeftNeighbor: true,
          leftNeighbor: true,
          topLeftNeighbor: true,
        },
      },
    ];