import { SpriteTile } from "../models/map";

export const trees: SpriteTile[] = [
  {
    id: "treeClumpTopLeft",
    spriteGridPosX: 0,
    spriteGridPosY: 0,
    tileHeight: 1,
    tileWidth: 1,
    tileOffsetX: -16,
    tileOffsetY: -64,
    obstacleObstructionX: 1,
    obstacleObstructionY: 1,
    drawWhen: {
      topNeighbor: false,
      topRightNeighbor: null,
      rightNeighbor: true,
      bottomRightNeighbor: null,
      bottomNeighbor: true,
      bottomLeftNeighbor: null,
      leftNeighbor: false,
      topLeftNeighbor: false,
    }
  },
  {
    id: "treeClumpTopCenter",
    spriteGridPosX: 1,
    spriteGridPosY: 0,
    tileHeight: 1,
    tileWidth: 1,
    tileOffsetX: -16,
    tileOffsetY: -64,
    obstacleObstructionX: 1,
    obstacleObstructionY: 1,
    drawWhen: {
      topNeighbor: false,
      topRightNeighbor: null,
      rightNeighbor: true,
      bottomRightNeighbor: true,
      bottomNeighbor: true,
      bottomLeftNeighbor: true,
      leftNeighbor: true,
      topLeftNeighbor: null,
    }
  }, {
    id: "treeClumpTopRight",
    spriteGridPosX: 2,
    spriteGridPosY: 0,
    tileHeight: 1,
    tileWidth: 1,
    tileOffsetX: -16,
    tileOffsetY: -64,
    obstacleObstructionX: 1,
    obstacleObstructionY: 1,
    drawWhen: {
      topNeighbor: false,
      topRightNeighbor: false,
      rightNeighbor: false,
      bottomRightNeighbor: null,
      bottomNeighbor: true,
      bottomLeftNeighbor: null,
      leftNeighbor: true,
      topLeftNeighbor: null,
    }
  },
  {
    id: "treeClumpGrowableLeft",
    spriteGridPosX: 0,
    spriteGridPosY: 1,
    tileHeight: 1,
    tileWidth: 1,
    tileOffsetX: -16,
    tileOffsetY: -64,
    obstacleObstructionX: 1,
    obstacleObstructionY: 1,
    drawWhen: {
      topNeighbor: true,
      topRightNeighbor: null,
      rightNeighbor: true,
      bottomRightNeighbor: null,
      bottomNeighbor: true,
      bottomLeftNeighbor: null,
      leftNeighbor: false,
      topLeftNeighbor: false, // this one
    }
  }, {
    id: "treeClumpGrowableCenter",
    spriteGridPosX: 1,
    spriteGridPosY: 1,
    tileHeight: 1,
    tileWidth: 1,
    tileOffsetX: -16,
    tileOffsetY: -64,
    obstacleObstructionX: 1,
    obstacleObstructionY: 1,
    drawWhen: {
      topNeighbor: true,
      topRightNeighbor: true,
      rightNeighbor: true,
      bottomRightNeighbor: true,
      bottomNeighbor: true,
      bottomLeftNeighbor: true,
      leftNeighbor: true,
      topLeftNeighbor: true,
    }

  }, {
    id: "treeClumpGrowableRight",
    spriteGridPosX: 2,
    spriteGridPosY: 1,
    tileHeight: 1,
    tileWidth: 1,
    tileOffsetX: -16,
    tileOffsetY: -64,
    obstacleObstructionX: 1,
    obstacleObstructionY: 1,
    drawWhen: {
      topNeighbor: true,
      topRightNeighbor: false,
      rightNeighbor: false,
      bottomRightNeighbor: null,
      bottomNeighbor: true,
      bottomLeftNeighbor: null,
      leftNeighbor: true,
      topLeftNeighbor: null,
    }
  }, {
    id: "treeClumpTrunkLeft",
    spriteGridPosX: 2,
    spriteGridPosY: 3,
    tileHeight: 3,
    tileWidth: 1,
    tileOffsetX: -16,
    tileOffsetY: -64,
    obstacleObstructionX: 1,
    obstacleObstructionY: 1,
    drawWhen: {
      topNeighbor: null,
      topRightNeighbor: null,
      rightNeighbor: true,
      bottomRightNeighbor: null,
      bottomNeighbor: false,
      bottomLeftNeighbor: false,
      leftNeighbor: false,
      topLeftNeighbor: false,
    }
  },
  {
    id: "treeClumpTrunkCenter",
    default: true,
    spriteGridPosX: 3,
    spriteGridPosY: 3,
    tileHeight: 3,
    tileWidth: 1,
    tileOffsetX: -16,
    tileOffsetY: -64,
    obstacleObstructionX: 1,
    obstacleObstructionY: 1,
    drawWhen: {
      topNeighbor: null,
      topRightNeighbor: null,
      rightNeighbor: true,
      bottomRightNeighbor: null,
      bottomNeighbor: false,
      bottomLeftNeighbor: null,
      leftNeighbor: true,
      topLeftNeighbor: null,
    }
  },
  {
    id: "treeClumpTrunkRight",
    spriteGridPosX: 4,
    spriteGridPosY: 3,
    tileHeight: 3,
    tileWidth: 1,
    tileOffsetX: -16,
    tileOffsetY: -64,
    obstacleObstructionX: 1,
    obstacleObstructionY: 1,
    drawWhen: {
      topNeighbor: null,
      topRightNeighbor: false,
      rightNeighbor: false,
      bottomRightNeighbor: false,
      bottomNeighbor: false,
      bottomLeftNeighbor: null,
      leftNeighbor: true,
      topLeftNeighbor: null,
    }
  },
  {
    id: "treeClumpTrunkLeftAngle",
    spriteGridPosX: 1,
    spriteGridPosY: 3,
    tileHeight: 3,
    tileWidth: 1,
    tileOffsetX: -16,
    tileOffsetY: -64,
    obstacleObstructionX: 1,
    obstacleObstructionY: 1,
    drawWhen: {
      topNeighbor: null,
      topRightNeighbor: null,
      rightNeighbor: true,
      bottomRightNeighbor: null,
      bottomNeighbor: false,
      bottomLeftNeighbor: false,
      leftNeighbor: false,
      topLeftNeighbor: true,
    }
  },
  {
    id: "treeClumpTrunkRightAngle",
    spriteGridPosX: 5,
    spriteGridPosY: 3,
    tileHeight: 3,
    tileWidth: 1,
    tileOffsetX: -16,
    tileOffsetY: -64,
    obstacleObstructionX: 1,
    obstacleObstructionY: 1,
    drawWhen: {
      topNeighbor: null,
      topRightNeighbor: true,
      rightNeighbor: false,
      bottomRightNeighbor: false,
      bottomNeighbor: false,
      bottomLeftNeighbor: null,
      leftNeighbor: true,
      topLeftNeighbor: null,
    }
  },
  {
    id: "treeClumpLeftFillerAngle",
    spriteGridPosX: 6,
    spriteGridPosY: 0,
    tileHeight: 1,
    tileWidth: 1,
    tileOffsetX: -16,
    tileOffsetY: -64,
    obstacleObstructionX: 1,
    obstacleObstructionY: 1,
    drawWhen: {
      topNeighbor: true,
      topRightNeighbor: true,
      rightNeighbor: true,
      bottomRightNeighbor: false,
      bottomNeighbor: true,
      bottomLeftNeighbor: true,
      leftNeighbor: true,
      topLeftNeighbor: true,

    }
  },
  {
    id: "treeClumpRightFillerAngle",
    spriteGridPosX: 7,
    spriteGridPosY: 0,
    tileHeight: 1,
    tileWidth: 1,
    tileOffsetX: -16,
    tileOffsetY: -64,
    obstacleObstructionX: 1,
    obstacleObstructionY: 1,
    drawWhen: {

      topNeighbor: true,
      topRightNeighbor: true,
      rightNeighbor: true,
      bottomRightNeighbor: true,
      bottomNeighbor: true,
      bottomLeftNeighbor: false,
      leftNeighbor: true,
      topLeftNeighbor: true,
    }
  },
  {
    id: "treeClumpLeftFillerAngleUP",
    spriteGridPosX: 6,
    spriteGridPosY: 1,
    tileHeight: 1,
    tileWidth: 1,
    tileOffsetX: -16,
    tileOffsetY: -64,
    obstacleObstructionX: 1,
    obstacleObstructionY: 1,
    drawWhen: {
      topNeighbor: true,
      topRightNeighbor: false,
      rightNeighbor: true,
      bottomRightNeighbor: true,
      bottomNeighbor: true,
      bottomLeftNeighbor: true,
      leftNeighbor: true,
      topLeftNeighbor: true,

    }
  },
  {
    id: "treeClumpRightFillerAngleUp",
    spriteGridPosX: 7,
    spriteGridPosY: 1,
    tileHeight: 1,
    tileWidth: 1,
    tileOffsetX: -16,
    tileOffsetY: -64,
    obstacleObstructionX: 1,
    obstacleObstructionY: 1,
    drawWhen: {
      topNeighbor: true,
      topRightNeighbor: true,
      rightNeighbor: true,
      bottomRightNeighbor: true,
      bottomNeighbor: true,
      bottomLeftNeighbor: true,
      leftNeighbor: true,
      topLeftNeighbor: false,
    }
  },
  {
    id: "treeClumpRightAngleGapFiller",
    spriteGridPosX: 6,
    spriteGridPosY: 4,
    tileHeight: 2, 
    tileWidth: 1,
    tileOffsetX: -16,
    tileOffsetY: -64,
    obstacleObstructionX: 1,
    obstacleObstructionY: 1,
    drawWhen: {
      topNeighbor: true,
      topRightNeighbor: true,
      rightNeighbor: false,
      bottomRightNeighbor: false,
      bottomNeighbor: true,
      bottomLeftNeighbor: true,
      leftNeighbor: true,
      topLeftNeighbor: true,
    } 
  },
  {
    id: "treeClumpLeftAngleGapFiller",
    spriteGridPosX: 7,
    spriteGridPosY: 4,
    tileHeight: 2, 
    tileWidth: 1,
    tileOffsetX: -16,
    tileOffsetY: -64,
    obstacleObstructionX: 1,
    obstacleObstructionY: 1,
    drawWhen: {
      topNeighbor: true,
      topRightNeighbor: true,
      rightNeighbor: true,
      bottomRightNeighbor: true,
      bottomNeighbor: true,
      bottomLeftNeighbor: false,
      leftNeighbor: false,
      topLeftNeighbor: true,
    } 
  },
  {
    id: "treeClumpLeftFillerAngleSingle",
    spriteGridPosX: 7,
    spriteGridPosY: 4,
    tileHeight: 1,
    tileWidth: 1,
    tileOffsetX: -16,
    tileOffsetY: -64,
    obstacleObstructionX: 1,
    obstacleObstructionY: 1,
    drawWhen: {
      topNeighbor: true,
      topRightNeighbor: true,
      rightNeighbor: true,
      bottomRightNeighbor: true,
      bottomNeighbor: true,
      bottomLeftNeighbor: true,
      leftNeighbor: false,
      topLeftNeighbor: true,
    } 
  },
  {
    id: "treeClumpRightFillerAngleSingle",
    spriteGridPosX: 6,
    spriteGridPosY: 4,
    tileHeight: 1,
    tileWidth: 1,
    tileOffsetX: -16,
    tileOffsetY: -64,
    obstacleObstructionX: 1,
    obstacleObstructionY: 1,
    drawWhen: {
      topNeighbor: true,
      topRightNeighbor: true,
      rightNeighbor: false,
      bottomRightNeighbor: true,
      bottomNeighbor: true,
      bottomLeftNeighbor: true,
      leftNeighbor: true,
      topLeftNeighbor: true,
    } 
  },
]
