import { TerrainTile } from "../models/sprite-tile.model";

export const trees: TerrainTile[] = [
  {
    id: "treeClumpTopLeft",
    spritePosX: 0,
    spritePosY: 0,
    spriteSize: {x: 16, y: 16},
    offsetX: 0,
    offsetY: -32,
    drawWhen: {
      topNeighbor: false,
      topRightNeighbor: null,
      rightNeighbor: true,
      bottomRightNeighbor: null,
      bottomNeighbor: true,
      bottomLeftNeighbor: null,
      leftNeighbor: false,
      topLeftNeighbor: false,
    }
  },
  {
    id: "treeClumpTopCenter",
    spritePosX: 1,
    spritePosY: 0,
    spriteSize: {x: 16, y: 16},
    offsetX: 0,
    offsetY: -32,
    drawWhen: {
      topNeighbor: false,
      topRightNeighbor: null,
      rightNeighbor: true,
      bottomRightNeighbor: true,
      bottomNeighbor: true,
      bottomLeftNeighbor: true,
      leftNeighbor: true,
      topLeftNeighbor: null,
    }
  }, {
    id: "treeClumpTopRight",
    spritePosX: 2,
    spritePosY: 0,
    spriteSize: {x: 16, y: 16},
    offsetX: 0,
    offsetY: -32,
    drawWhen: {
      topNeighbor: false,
      topRightNeighbor: false,
      rightNeighbor: false,
      bottomRightNeighbor: null,
      bottomNeighbor: true,
      bottomLeftNeighbor: null,
      leftNeighbor: true,
      topLeftNeighbor: null,
    }
  },
  {
    id: "treeClumpGrowableLeft",
    spritePosX: 0,
    spritePosY: 1,
    spriteSize: {x: 16, y: 16},
    offsetX: 0,
    offsetY: -32,
    drawWhen: {
      topNeighbor: true,
      topRightNeighbor: null,
      rightNeighbor: true,
      bottomRightNeighbor: null,
      bottomNeighbor: true,
      bottomLeftNeighbor: null,
      leftNeighbor: false,
      topLeftNeighbor: false, // this one
    }
  }, {
    id: "treeClumpGrowableCenter",
    spritePosX: 1,
    spritePosY: 1,
    spriteSize: {x: 16, y: 16},
    offsetX: 0,
    offsetY: -32,
    drawWhen: {
      topNeighbor: true,
      topRightNeighbor: true,
      rightNeighbor: true,
      bottomRightNeighbor: true,
      bottomNeighbor: true,
      bottomLeftNeighbor: true,
      leftNeighbor: true,
      topLeftNeighbor: true,
    }

  }, {
    id: "treeClumpGrowableRight",
    spritePosX: 2,
    spritePosY: 1,
    spriteSize: {x: 16, y: 16},
    offsetX: 0,
    offsetY: -32,
    drawWhen: {
      topNeighbor: true,
      topRightNeighbor: false,
      rightNeighbor: false,
      bottomRightNeighbor: null,
      bottomNeighbor: true,
      bottomLeftNeighbor: null,
      leftNeighbor: true,
      topLeftNeighbor: null,
    }
  }, {
    id: "treeClumpTrunkLeft",
    spritePosX: 2,
    spritePosY: 3,
    spriteSize: {x: 16, y: 48},
    offsetX: 0,
    offsetY: -32,
    drawWhen: {
      topNeighbor: null,
      topRightNeighbor: null,
      rightNeighbor: true,
      bottomRightNeighbor: null,
      bottomNeighbor: false,
      bottomLeftNeighbor: false,
      leftNeighbor: false,
      topLeftNeighbor: false,
    }
  },
  {
    id: "treeClumpTrunkCenter",
    default: true,
    spritePosX: 3,
    spritePosY: 3,
    spriteSize: {x: 16, y: 48},
    offsetX: 0,
    offsetY: -32,
    drawWhen: {
      topNeighbor: null,
      topRightNeighbor: null,
      rightNeighbor: true,
      bottomRightNeighbor: null,
      bottomNeighbor: false,
      bottomLeftNeighbor: null,
      leftNeighbor: true,
      topLeftNeighbor: null,
    }
  },
  {
    id: "treeClumpTrunkRight",
    spritePosX: 4,
    spritePosY: 3,
    spriteSize: {x: 16, y: 48},
    offsetX: 0,
    offsetY: -32,
    drawWhen: {
      topNeighbor: null,
      topRightNeighbor: false,
      rightNeighbor: false,
      bottomRightNeighbor: false,
      bottomNeighbor: false,
      bottomLeftNeighbor: null,
      leftNeighbor: true,
      topLeftNeighbor: null,
    }
  },
  {
    id: "treeClumpTrunkLeftAngle",
    spritePosX: 1,
    spritePosY: 3,
    spriteSize: {x: 16, y: 48},
    offsetX: 0,
    offsetY: -32,
    drawWhen: {
      topNeighbor: null,
      topRightNeighbor: null,
      rightNeighbor: true,
      bottomRightNeighbor: null,
      bottomNeighbor: false,
      bottomLeftNeighbor: false,
      leftNeighbor: false,
      topLeftNeighbor: true,
    }
  },
  {
    id: "treeClumpTrunkRightAngle",
    spritePosX: 5,
    spritePosY: 3,
    spriteSize: {x: 16, y: 48},
    offsetX: 0,
    offsetY: -32,
    drawWhen: {
      topNeighbor: null,
      topRightNeighbor: true,
      rightNeighbor: false,
      bottomRightNeighbor: false,
      bottomNeighbor: false,
      bottomLeftNeighbor: null,
      leftNeighbor: true,
      topLeftNeighbor: null,
    }
  },
  {
    id: "treeClumpLeftFillerAngle",
    spritePosX: 6,
    spritePosY: 0,
    spriteSize: {x: 16, y: 16},
    offsetX: 0,
    offsetY: -32,
    drawWhen: {
      topNeighbor: true,
      topRightNeighbor: true,
      rightNeighbor: true,
      bottomRightNeighbor: false,
      bottomNeighbor: true,
      bottomLeftNeighbor: true,
      leftNeighbor: true,
      topLeftNeighbor: true,

    }
  },
  {
    id: "treeClumpRightFillerAngle",
    spritePosX: 7,
    spritePosY: 0,
    spriteSize: {x: 16, y: 16},
    offsetX: 0,
    offsetY: -32,
    drawWhen: {
      topNeighbor: true,
      topRightNeighbor: true,
      rightNeighbor: true,
      bottomRightNeighbor: true,
      bottomNeighbor: true,
      bottomLeftNeighbor: false,
      leftNeighbor: true,
      topLeftNeighbor: true,
    }
  },
  {
    id: "treeClumpLeftFillerAngleUP",
    spritePosX: 6,
    spritePosY: 1,
    spriteSize: {x: 16, y: 16},
    offsetX: 0,
    offsetY: -32,
    drawWhen: {
      topNeighbor: true,
      topRightNeighbor: false,
      rightNeighbor: true,
      bottomRightNeighbor: true,
      bottomNeighbor: true,
      bottomLeftNeighbor: true,
      leftNeighbor: true,
      topLeftNeighbor: true,

    }
  },
  {
    id: "treeClumpRightFillerAngleUp",
    spritePosX: 7,
    spritePosY: 1,
    spriteSize: {x: 16, y: 16},
    offsetX: 0,
    offsetY: -32,
    drawWhen: {
      topNeighbor: true,
      topRightNeighbor: true,
      rightNeighbor: true,
      bottomRightNeighbor: true,
      bottomNeighbor: true,
      bottomLeftNeighbor: true,
      leftNeighbor: true,
      topLeftNeighbor: false,
    }
  },
  {
    id: "treeClumpRightAngleGapFiller",
    spritePosX: 6,
    spritePosY: 4,
    spriteSize: {x: 16, y: 32},
    offsetX: 0,
    offsetY: -32,
    drawWhen: {
      topNeighbor: true,
      topRightNeighbor: true,
      rightNeighbor: false,
      bottomRightNeighbor: false,
      bottomNeighbor: true,
      bottomLeftNeighbor: true,
      leftNeighbor: true,
      topLeftNeighbor: true,
    } 
  },
  {
    id: "treeClumpLeftAngleGapFiller",
    spritePosX: 7,
    spritePosY: 4,
    spriteSize: {x: 16, y: 32},
    offsetX: 0,
    offsetY: -32,
    drawWhen: {
      topNeighbor: true,
      topRightNeighbor: true,
      rightNeighbor: true,
      bottomRightNeighbor: true,
      bottomNeighbor: true,
      bottomLeftNeighbor: false,
      leftNeighbor: false,
      topLeftNeighbor: true,
    } 
  },
  {
    id: "treeClumpLeftFillerAngleSingle",
    spritePosX: 7,
    spritePosY: 4,
    spriteSize: {x: 16, y: 16},
    offsetX: 0,
    offsetY: -32,
    drawWhen: {
      topNeighbor: true,
      topRightNeighbor: true,
      rightNeighbor: true,
      bottomRightNeighbor: true,
      bottomNeighbor: true,
      bottomLeftNeighbor: true,
      leftNeighbor: false,
      topLeftNeighbor: true,
    } 
  },
  {
    id: "treeClumpRightFillerAngleSingle",
    spritePosX: 6,
    spritePosY: 4,
    spriteSize: {x: 16, y: 16},
    offsetX: 0,
    offsetY: -32,
    drawWhen: {
      topNeighbor: true,
      topRightNeighbor: true,
      rightNeighbor: false,
      bottomRightNeighbor: true,
      bottomNeighbor: true,
      bottomLeftNeighbor: true,
      leftNeighbor: true,
      topLeftNeighbor: true,
    } 
  }  
]
