import { TerrainTile } from "../models/sprite-tile.model";

export const trees: TerrainTile[] = [
  {
    id: "treeClumpTopLeft",
    spriteX: 0,
    spriteY: 0,
    // spriteSize: {x: 1, y: 1},
    offsetX: 0,
    offsetY: -32,
    drawWhen: {
      topNeighbor: false,
      topRightNeighbor: null,
      rightNeighbor: true,
      bottomRightNeighbor: null,
      bottomNeighbor: true,
      bottomLeftNeighbor: null,
      leftNeighbor: false,
      topLeftNeighbor: false,
    }
  },
  {
    id: "treeClumpTopCenter",
    spriteX: 1,
    spriteY: 0,
    // spriteSize: {x: 1, y: 1},
    offsetX: 0,
    offsetY: -32,
    drawWhen: {
      topNeighbor: false,
      topRightNeighbor: null,
      rightNeighbor: true,
      bottomRightNeighbor: true,
      bottomNeighbor: true,
      bottomLeftNeighbor: true,
      leftNeighbor: true,
      topLeftNeighbor: null,
    }
  }, {
    id: "treeClumpTopRight",
    spriteX: 2,
    spriteY: 0,
    // spriteSize: {x: 1, y: 1},
    offsetX: 0,
    offsetY: -32,
    drawWhen: {
      topNeighbor: false,
      topRightNeighbor: false,
      rightNeighbor: false,
      bottomRightNeighbor: null,
      bottomNeighbor: true,
      bottomLeftNeighbor: null,
      leftNeighbor: true,
      topLeftNeighbor: null,
    }
  },
  {
    id: "treeClumpGrowableLeft",
    spriteX: 0,
    spriteY: 1,
    // spriteSize: {x: 1, y: 1},
    offsetX: 0,
    offsetY: -32,
    drawWhen: {
      topNeighbor: true,
      topRightNeighbor: null,
      rightNeighbor: true,
      bottomRightNeighbor: null,
      bottomNeighbor: true,
      bottomLeftNeighbor: null,
      leftNeighbor: false,
      topLeftNeighbor: false, // this one
    }
  }, {
    id: "treeClumpGrowableCenter",
    spriteX: 1,
    spriteY: 1,
    // spriteSize: {x: 1, y: 1},
    offsetX: 0,
    offsetY: -32,
    drawWhen: {
      topNeighbor: true,
      topRightNeighbor: true,
      rightNeighbor: true,
      bottomRightNeighbor: true,
      bottomNeighbor: true,
      bottomLeftNeighbor: true,
      leftNeighbor: true,
      topLeftNeighbor: true,
    }

  }, {
    id: "treeClumpGrowableRight",
    spriteX: 2,
    spriteY: 1,
    // spriteSize: {x: 1, y: 1},
    offsetX: 0,
    offsetY: -32,
    drawWhen: {
      topNeighbor: true,
      topRightNeighbor: false,
      rightNeighbor: false,
      bottomRightNeighbor: null,
      bottomNeighbor: true,
      bottomLeftNeighbor: null,
      leftNeighbor: true,
      topLeftNeighbor: null,
    }
  }, {
    id: "treeClumpTrunkLeft",
    spriteX: 2,
    spriteY: 3,
    // spriteSize: {x: 1, y: 3},
    offsetX: 0,
    offsetY: -32,
    drawWhen: {
      topNeighbor: null,
      topRightNeighbor: null,
      rightNeighbor: true,
      bottomRightNeighbor: null,
      bottomNeighbor: false,
      bottomLeftNeighbor: false,
      leftNeighbor: false,
      topLeftNeighbor: false,
    }
  },
  {
    id: "treeClumpTrunkCenter",
    default: true,
    spriteX: 3,
    spriteY: 3,
    // spriteSize: {x: 1, y: 3},
    offsetX: 0,
    offsetY: -32,
    drawWhen: {
      topNeighbor: null,
      topRightNeighbor: null,
      rightNeighbor: true,
      bottomRightNeighbor: null,
      bottomNeighbor: false,
      bottomLeftNeighbor: null,
      leftNeighbor: true,
      topLeftNeighbor: null,
    }
  },
  {
    id: "treeClumpTrunkRight",
    spriteX: 4,
    spriteY: 3,
    // spriteSize: {x: 1, y: 3},
    offsetX: 0,
    offsetY: -32,
    drawWhen: {
      topNeighbor: null,
      topRightNeighbor: false,
      rightNeighbor: false,
      bottomRightNeighbor: false,
      bottomNeighbor: false,
      bottomLeftNeighbor: null,
      leftNeighbor: true,
      topLeftNeighbor: null,
    }
  },
  {
    id: "treeClumpTrunkLeftAngle",
    spriteX: 1,
    spriteY: 3,
    // spriteSize: {x: 1, y: 3},
    offsetX: 0,
    offsetY: -32,
    drawWhen: {
      topNeighbor: null,
      topRightNeighbor: null,
      rightNeighbor: true,
      bottomRightNeighbor: null,
      bottomNeighbor: false,
      bottomLeftNeighbor: false,
      leftNeighbor: false,
      topLeftNeighbor: true,
    }
  },
  {
    id: "treeClumpTrunkRightAngle",
    spriteX: 5,
    spriteY: 3,
    // spriteSize: {x: 1, y: 3},
    offsetX: 0,
    offsetY: -32,
    drawWhen: {
      topNeighbor: null,
      topRightNeighbor: true,
      rightNeighbor: false,
      bottomRightNeighbor: false,
      bottomNeighbor: false,
      bottomLeftNeighbor: null,
      leftNeighbor: true,
      topLeftNeighbor: null,
    }
  },
  {
    id: "treeClumpLeftFillerAngle",
    spriteX: 6,
    spriteY: 0,
    // spriteSize: {x: 1, y: 1},
    offsetX: 0,
    offsetY: -32,
    drawWhen: {
      topNeighbor: true,
      topRightNeighbor: true,
      rightNeighbor: true,
      bottomRightNeighbor: false,
      bottomNeighbor: true,
      bottomLeftNeighbor: true,
      leftNeighbor: true,
      topLeftNeighbor: true,

    }
  },
  {
    id: "treeClumpRightFillerAngle",
    spriteX: 7,
    spriteY: 0,
    // spriteSize: {x: 1, y: 1},
    offsetX: 0,
    offsetY: -32,
    drawWhen: {
      topNeighbor: true,
      topRightNeighbor: true,
      rightNeighbor: true,
      bottomRightNeighbor: true,
      bottomNeighbor: true,
      bottomLeftNeighbor: false,
      leftNeighbor: true,
      topLeftNeighbor: true,
    }
  },
  {
    id: "treeClumpLeftFillerAngleUP",
    spriteX: 6,
    spriteY: 1,
    // spriteSize: {x: 1, y: 1},
    offsetX: 0,
    offsetY: -32,
    drawWhen: {
      topNeighbor: true,
      topRightNeighbor: false,
      rightNeighbor: true,
      bottomRightNeighbor: true,
      bottomNeighbor: true,
      bottomLeftNeighbor: true,
      leftNeighbor: true,
      topLeftNeighbor: true,

    }
  },
  {
    id: "treeClumpRightFillerAngleUp",
    spriteX: 7,
    spriteY: 1,
    // spriteSize: {x: 1, y: 1},
    offsetX: 0,
    offsetY: -32,
    drawWhen: {
      topNeighbor: true,
      topRightNeighbor: true,
      rightNeighbor: true,
      bottomRightNeighbor: true,
      bottomNeighbor: true,
      bottomLeftNeighbor: true,
      leftNeighbor: true,
      topLeftNeighbor: false,
    }
  },
  {
    id: "treeClumpRightAngleGapFiller",
    spriteX: 6,
    spriteY: 4,
    // spriteSize: {x: 1, y: 2},
    offsetX: 0,
    offsetY: -32,
    drawWhen: {
      topNeighbor: true,
      topRightNeighbor: true,
      rightNeighbor: false,
      bottomRightNeighbor: false,
      bottomNeighbor: true,
      bottomLeftNeighbor: true,
      leftNeighbor: true,
      topLeftNeighbor: true,
    } 
  },
  {
    id: "treeClumpLeftAngleGapFiller",
    spriteX: 7,
    spriteY: 4,
    // spriteSize: {x: 1, y: 2},
    offsetX: 0,
    offsetY: -32,
    drawWhen: {
      topNeighbor: true,
      topRightNeighbor: true,
      rightNeighbor: true,
      bottomRightNeighbor: true,
      bottomNeighbor: true,
      bottomLeftNeighbor: false,
      leftNeighbor: false,
      topLeftNeighbor: true,
    } 
  },
  {
    id: "treeClumpLeftFillerAngleSingle",
    spriteX: 7,
    spriteY: 4,
    // spriteSize: {x: 1, y: 1},
    offsetX: 0,
    offsetY: -32,
    drawWhen: {
      topNeighbor: true,
      topRightNeighbor: true,
      rightNeighbor: true,
      bottomRightNeighbor: true,
      bottomNeighbor: true,
      bottomLeftNeighbor: true,
      leftNeighbor: false,
      topLeftNeighbor: true,
    } 
  },
  {
    id: "treeClumpRightFillerAngleSingle",
    spriteX: 6,
    spriteY: 4,
    // spriteSize: {x: 1, y: 1},
    offsetX: 0,
    offsetY: -32,
    drawWhen: {
      topNeighbor: true,
      topRightNeighbor: true,
      rightNeighbor: false,
      bottomRightNeighbor: true,
      bottomNeighbor: true,
      bottomLeftNeighbor: true,
      leftNeighbor: true,
      topLeftNeighbor: true,
    } 
  }  
]
